[package]
edition = "2024"
name = "xtask"
version = "0.1.0"

[target.'cfg(any(windows, unix))'.dependencies]

anyhow = "1.0"
cargo_metadata = "0.23"
chrono = "0.4"
clap = {version = "4.4", features = ["derive"]}
colored = "3"
jkconfig = "0.1"
ostool = "0.8"
reqwest = "0.12"
schemars = {version = "1", features = ["derive"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1"
sha2 = "0.10"
tokio = {version = "1", features = ["full"]}
toml.workspace = true
zerocopy = "=0.8.28"
# adapt nightly-2025-05-20
axvmconfig = {workspace = true, features = ["std"]}
tar = "0.4"
flate2 = "1.0"
