[package]
edition = "2024"
name = "axplat-riscv64-qemu-virt"
version = "0.2.0"

[features]
default = [
  "irq",
  "smp",
]
fp-simd = ["axcpu/fp-simd"]
irq = ["axplat/irq"]
rtc = ["riscv_goldfish"]
smp = ["axplat/smp"]

[dependencies]
log = "0.4"
riscv = "0.15.0"
sbi-rt = { version = "0.0.3", features = ["legacy"] }
riscv_goldfish = { version = "0.1", optional = true }

axconfig-macros = "0.2"
axcpu = "0.2"
axplat = { workspace = true }

[package.metadata.docs.rs]
targets = ["riscv64gc-unknown-none-elf"]
